### ISSUE TITLE
returning mulitple images

### ISSUE THREAD

**Issue by jorivankeulen** [SaifurRahmanMohsin/RESTful-Plugin#4]
I have created a Builder plugin which allows for multple images to be uploaded to a single record, using: 

`    public $attachMany = [
        'images' => 'System\Models\File',
        'order' => 'sort_oder'
    ];
`

Each image is stored in the `system_files` table, and for what i can see related through attachment_type and attachment_id.
The backend menu shows all the images, but i can't figure how to return them through the API controller.
Now i just get `images: null` 

In the RestController.php script i found:
`        $relations =  isset($this->config->allowedActions['show']['relations']) ? $this->config->allowedActions['show']['relations'] : [];
`
But I don't understand how to correctly configure the API for this to work. Can anyone help me with this?

**Comment by SaifurRahmanMohsin** [comment]
It works fine for me. I just installed my own plugin [Magnific Gallery](http://octobercms.com/plugin/mohsin-magnificgallery) and uploaded a couple of images (which is internally defined as a relation called **images** just like how you did it). I scaffolded a RESTful controller for the existing Galleries controller of the Magnific Gallery plugin using the command: `php artisan create:restcontroller Mohsin.MagnificGallery Gallery` and then changed the REST config file to look like this:
```
# ===================================
#  Rest Behavior Config
# ===================================

# Allowed Rest Actions
allowedActions:
  index:
      pageSize: 20
      relations: images

# Model Class name
modelClass: Mohsin\MagnificGallery\Models\Gallery

```

The output works as expected and gives the links in addition to the other fields. Here’s a screenshot.

<img width="1440" alt="screen shot 2016-11-20 at 17 03 57" src="https://cloud.githubusercontent.com/assets/1699753/20462409/710ed14c-af43-11e6-8598-e0a32d122d80.png">
